---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/os-image-stemcell-builder

inputs:
  - name: bosh-linux-stemcell-builder

outputs:
- name: os-image

run:
  path: bosh-linux-stemcell-builder/ci/os-images/tasks/build.sh

params:
  OPERATING_SYSTEM_NAME:      replace-me
  OPERATING_SYSTEM_VERSION:   replace-me
