platform: linux

image_resource:
  type: docker-image
  source: {repository: bosh/main}

inputs:
- name: bosh-linux-stemcell-builder
- name: bosh-cli
- name: stemcell
- name: syslog-release
- name: os-conf-release
- name: director-state

run:
  path: bosh-linux-stemcell-builder/ci/tasks/test-stemcell.sh
params:
  package: .
